volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis_data: {}



services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: my_awesome_project_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: my_awesome_project_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres


  celeryworker:
    <<: *django
    image: my_awesome_project_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: my_awesome_project_production_celerybeat
    command: /start-celerybeat

